version: "3.2"
services:
  prod:
    container_name: esquire-prod
    build:
      context: .
      dockerfile: Dockerfile-prod
    ports:
      - 5000:5000
    environment:
      - NODE_ENV=production
