version: "3.2"
services:
  dev:
    container_name: esquire-dev
    build:
      context: .
      dockerfile: Dockerfile
    image: esquire-dev
    ports:
      - 3000:3000
    volumes:
      - /usr/src/app/node_modules/
      - .:/usr/src/app
    environment:
      - NODE_ENV=development
