version: "3.2"
services:
  dev:
    container_name: esquire-dev
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    environment:
      - NODE_ENV=development
  prod:
    container_name: esquire-prod
    build:
      context: .
      dockerfile: Dockerfile-prod
    ports:
      - 5000:5000
    environment:
      - NODE_ENV=production
